name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    name: "Build and Publish Docker Image"

    steps:
    - uses: actions/checkout@v4
    - build:
      - name: "Build"
      - run: |
        go build
    - test:
      - name: "Test"
      - run: |
        go test -v

  publish:
    runs-on: ubuntu-latest
    name: "Build and Publish Docker Image"

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker build . --file Dockerfile --tag seidlfs/my-hello:latest
        docker tag seidlfs/my-hello:latest seidlfs/my-hello:$GIT_SHA
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
        docker image push seidlfs/my-hello:$GIT_SHA
        
        
