name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag seidlfs/my-hello:latest

    - name: Login to DockerHub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run:
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Push Image
      run: 
        GIT_SHA=$(git rev-parse --short HEAD)"
        docker tag seidlfs/my-hello:lastest seidlfs/my-hello:$GIT_SHA
        docker push seidlfs/my-hello:$GIT_SHA
        
