name: Docker Image CI

on:
  push:
    branches: [ "pipeline" ]
  pull_request:
    branches: [ "pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"

    steps:
    - uses: actions/checkout@v4
    - run: |
        go build
  test:
    runs-on: ubuntu-latest
    name: "Test"
    needs: build

    steps:
      - uses: actions/checkout@v4
      - run: |
          go test -v

  publish:
    runs-on: ubuntu-latest
    name: "Build and Publish Docker Image"
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Generate Image Tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker build . --file Dockerfile --tag seidlfs/my-hello:latest
        docker tag seidlfs/my-hello:latest seidlfs/my-hello:$GIT_SHA
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
        docker image push seidlfs/my-hello:$GIT_SHA
        docker image push seidlfs/my-hello:latest
  trivyScan:
      name: Scan for Vulnerabilities
      runs-on: ubuntu-20.04
      needs: publish
      steps:
        - name: Create Vars
          run: |
            GIT_SHA="$(git rev-parse --short HEAD)"
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.20.0
          with:
            image-ref: 'seidlfs/my-hello:${{ steps.vars.outputs.sha_short }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
        
        
